# All available relation types
types:
  - AccessibilityDifference
  - AffectedBy
  - AgriculturalTechnique
  - AlsoKnownByName
  - AlternativeOrReplacement
  - AppealRenewal
  - AsparagusColorVariety
  - AssignedTo
  - AssociatedWith
  - AttachedWith
  - AttendeeOfEvent
  - AvailableAtLocation
  - AwardedForFounding
  - BearsFoodIn
  - BellTimingInfo
  - BlanchingPurpose
  - BlanchingSource
  - BuriedInGround
  - CabbageHarvestingTime
  - CarrotContainerRelation
  - CategoryRelationship
  - CauseOf
  - Causes
  - ComparesTo
  - CompareTo
  - CompetitionStatus
  - CompetitivePressureFromExternalFactors
  - ConditionallyTriggered
  - ConditionsForSuccessfulOverwintering
  - ConstructingWindbreaks
  - ConsumerOf
  - Containment
  - ContainmentIssue
  - ContainmentLocation
  - Contains
  - ContainsMannequins
  - ContainsPaths
  - CreationTime
  - CropCharacteristic
  - CultivatedTaxonomyRelationship
  - DeficiencyRelationship
  - DependentOn
  - DiffersFromEntity
  - DuplicateTranslation
  - EarlierThan
  - EarlyHarvest
  - EdgeAssociation
  - ElevatedBy
  - Endogamy
  - EquipmentRelationship
  - ExemptFromSubstitution
  - ExemptFromTransplanting
  - FamilyRelationship
  - FarmEquipmentRelationship
  - FearResponse
  - FinancialExchange
  - FoundingDate
  - FrameAssociation
  - GerminationContext
  - GrowBelowGround
  - GrownIn
  - GrowthStageRelation
  - HairConduceiveToGrowth
  - HarvestedAt
  - HasAssociatedEntity
  - HasCharacteristic
  - HasDimensionalAttribute
  - HasDimensionalReach
  - HasHighMaintenanceRequirement
  - HasMonetaryValue
  - HasStructuralElements
  - HeatTransferRelationship
  - HighQuality
  - Hypernymy
  - ImpactOnDevelopment
  - InhibitsDevelopment
  - InstanceOf
  - IrrigationRelation
  - IsRelevantTo
  - LayeringRelationship
  - LeadPipeMaterialOrAlternative
  - LeftInPlace
  - LettuceTypeAssociation
  - LimitationRelationship
  - LocatedIn
  - LocationRelationship
  - ManagedByOrganizationOrTeam
  - ManureRelated
  - MarketingRelationship
  - MarketGardenerCharacteristics
  - MarketGardeningRelated
  - MaturityDateRelation
  - MeasurementRelation
  - MembershipRelationship
  - MilledToFinish
  - MonthlyComparisonOfSuccess
  - MonthlyOccurrence
  - MovedTo
  - MulchRelation
  - NotGrown
  - NotRelatedTo
  - OccursAt
  - OptionalRelationship
  - OriginatesFrom
  - OverlapsWith
  - PartOfRelationship
  - PeopleRelationshipEconomicActivity
  - PilesInWetlands
  - PlantableStatus
  - PlantedAt
  - PlantingRelationship
  - PoliceActionAffects
  - PracticeOf
  - Precedes
  - PreferredCondition
  - PreparationStatus
  - Produces
  - ProducesGuideFor
  - ProducesOutput
  - ProtectsFrom
  - ProtectionRelation
  - ProneToDegradation
  - PropagationMethod
  - PropagationSource
  - ProtectedOrCoveredWithMaterials
  - PruneRelation
  - RadishOrigin
  - RateOfChange
  - ReceiverOf
  - RegionSpecific
  - RelatedToFinancialInformation
  - RelatedToGardenLocations
  - RelatedToGreens
  - RemovalRelation
  - RemovedFrom
  - RemovableInSunlight
  - RentalLocation
  - RepositionsObjects
  - Requirement
  - Requires
  - ResistantTo
  - RetainsViabilityFor
  - SeasonalAssociation
  - SeasonalPattern
  - SeedingRelatedDestruction
  - SeedingRelationship
  - SelectedOrPicked
  - SequenceRelationship
  - SimilarityRelationship
  - SoilRelationship
  - SourceOfOrigins
  - SouthOriented
  - SpatialRelationship
  - SproutsFromLocation
  - StartedInvestigation
  - ThinningTechnique
  - TimeRelationship
  - TransplantationEvent
  - TransportationMethod
  - TreatedBy
  - TreatedWith
  - UsedWithPeas
  - Uses
  - UtilizedInContextOf
  - VariationOf
  - VisualRepresentation
  - WeatherSensitivity

