path: "/mnt/diskGum/manas/GOMgraph-main/data/18_Manuel_pratique_de_jardinage_-_Courtois_Gérard.txt"
group_id: "b18-llama70b"
source_description: "A widely used practical guide for vegetable, fruit, and ornamental gardening, updated across editions to reflect evolving horticultural knowledge."
reference_year: 1900 #not sure about the year
