path: "/mnt/diskGum/manas/GOMgraph-main/data/14_Ma_Pratique_de_la_culture_maraîchère.txt"
group_id: "b14-llama70b"
source_description: "A professional handbook detailing both open-air and forced vegetable cultivation, with calendars, tools, fertilization, and pest management."
reference_year: 1918 #1st editition
