path: "/mnt/diskGum/manas/GOMgraph-main/data/tomato_test/10_tomato.txt"
group_id: "10_tomato"
source_description: "A concise 1845 French manual detailing the techniques and principles of Parisian market gardening, by Moreau and Daverne."
reference_year: 1899 #3rd edition
