edge_type_map:
  "Entity,Entity":
    - AffectedBy
    - Causes
    - ResistantTo
    - Requires
    - Uses
    - LocatedInOrAt
    - OriginatesFrom
    - ContainsOrHasPart
    - PartOf
    - VarietyOf
    - TreatedWithSomething
    - ProtectionRelation
    - PlantedIn
    - GrowthStageRelatedTo
    - SeedingRelationship
    - PropagationMethod
    - Precedes
    - Follows
    - TemporalAssociation
    - SeasonalRelatedness
    - HasCharacteristic
    - HasMonetaryValue
    - ComparesTo
    - AlternativeOrReplacement
    - DiffersFrom
    - AssociatedWith
    - ProductionRelation

# edge_type_map:
#   "Entity,Entity":
#     - AccessibilityDifference
#     - AffectedBy
#     - AgriculturalTechnique
#     - AlsoKnownByName
#     - AlternativeOrReplacement
#     - AppealRenewal
#     - AsparagusColorVariety
#     - AssignedTo
#     - AssociatedWith
#     - AttachedWith
#     - AttendeeOfEvent
#     - AvailableAtLocation
#     - AwardedForFounding
#     - BearsFoodIn
#     - BellTimingInfo
#     - BlanchingPurpose
#     - BlanchingSource
#     - BuriedInGround
#     - CabbageHarvestingTime
#     - CarrotContainerRelation
#     - CategoryRelationship
#     - CauseOf
#     - Causes
#     - CompareTo
#     - ComparesTo
#     - CompetitionStatus
#     - CompetitivePressureFromExternalFactors
#     - ConditionallyTriggered
#     - ConditionsForSuccessfulOverwintering
#     - ConstructingWindbreaks
#     - ConsumerOf
#     - Containment
#     - ContainmentIssue
#     - ContainmentLocation
#     - Contains
#     - ContainsMannequins
#     - ContainsPaths
#     - CreationTime
#     - CropCharacteristic
#     - CultivatedTaxonomyRelationship
#     - DeficiencyRelationship
#     - DependentOn
#     - DiffersFromEntity
#     - DuplicateTranslation
#     - EarlierThan
#     - EarlyHarvest
#     - EdgeAssociation
#     - ElevatedBy
#     - Endogamy
#     - EquipmentRelationship
#     - ExemptFromSubstitution
#     - ExemptFromTransplanting
#     - FamilyRelationship
#     - FarmEquipmentRelationship
#     - FearResponse
#     - FinancialExchange
#     - FoundingDate
#     - FrameAssociation
#     - GerminationContext
#     - GrowBelowGround
#     - GrownIn
#     - GrowthStageRelation
#     - HairConduceiveToGrowth
#     - HarvestedAt
#     - HasAssociatedEntity
#     - HasCharacteristic
#     - HasDimensionalAttribute
#     - HasDimensionalReach
#     - HasHighMaintenanceRequirement
#     - HasMonetaryValue
#     - HasStructuralElements
#     - HeatTransferRelationship
#     - HighQuality
#     - Hypernymy
#     - ImpactOnDevelopment
#     - InhibitsDevelopment
#     - InstanceOf
#     - IrrigationRelation
#     - IsRelevantTo
#     - LayeringRelationship
#     - LeadPipeMaterialOrAlternative
#     - LeftInPlace
#     - LettuceTypeAssociation
#     - LimitationRelationship
#     - LocatedIn
#     - LocationRelationship
#     - ManagedByOrganizationOrTeam
#     - ManureRelated
#     - MarketingRelationship
#     - MarketGardenerCharacteristics
#     - MarketGardeningRelated
#     - MaturityDateRelation
#     - MeasurementRelation
#     - MembershipRelationship
#     - MilledToFinish
#     - MonthlyComparisonOfSuccess
#     - MonthlyOccurrence
#     - MovedTo
#     - MulchRelation
#     - NotGrown
#     - NotRelatedTo
#     - OccursAt
#     - OptionalRelationship
#     - OriginatesFrom
#     - OverlapsWith
#     - PartOfRelationship
#     - PeopleRelationshipEconomicActivity
#     - PilesInWetlands
#     - PlantableStatus
#     - PlantedAt
#     - PlantingRelationship
#     - PoliceActionAffects
#     - PracticeOf
#     - Precedes
#     - PreferredCondition
#     - PreparationStatus
#     - Produces
#     - ProducesGuideFor
#     - ProducesOutput
#     - PropagationMethod
#     - PropagationSource
#     - ProtectedOrCoveredWithMaterials
#     - ProtectionRelation
#     - ProtectsFrom
#     - ProneToDegradation
#     - PruneRelation
#     - RadishOrigin
#     - RateOfChange
#     - ReceiverOf
#     - RegionSpecific
#     - RelatedToFinancialInformation
#     - RelatedToGardenLocations
#     - RelatedToGreens
#     - RemovalRelation
#     - RemovableInSunlight
#     - RemovedFrom
#     - RentalLocation
#     - RepositionsObjects
#     - Requirement
#     - Requires
#     - ResistantTo
#     - RetainsViabilityFor
#     - SeasonalAssociation
#     - SeasonalPattern
#     - SeedingRelatedDestruction
#     - SeedingRelationship
#     - SelectedOrPicked
#     - SequenceRelationship
#     - SimilarityRelationship
#     - SoilRelationship
#     - SourceOfOrigins
#     - SouthOriented
#     - SpatialRelationship
#     - SproutsFromLocation
#     - StartedInvestigation
#     - ThinningTechnique
#     - TimeRelationship
#     - TransplantationEvent
#     - TransportationMethod
#     - TreatedBy
#     - TreatedWith
#     - UsedWithPeas
#     - Uses
#     - UtilizedInContextOf
#     - VariationOf
#     - VisualRepresentation
#     - WeatherSensitivity
#     - AffectedByAuthorityAction
#     - AimedAtProducingResourceFor
#     - AlsoKnownAs
#     - AssociatedWithOrganizationOrPersonnel
#     - AttendeeOfReligiousEvent
#     - AvailableInLocation
#     - AwardedPrize
#     - BasedOn
#     - BeforeRipeningOnVine
#     - BellRelatedInfo
#     - BlanchingBoundary
#     - CabbageHarvestingAge
#     - CarrotIsLocatedInOrOn
#     - CategoryOf
#     - CollarPosition
#     - CompareAttribute
#     - CompetitionFromExternalFactors
#     - ConditionsForSuccessfulGreenManureApplication
#     - ConsumptionRelation
#     - ContainMannequins
#     - ContainsOrHasPart
#     - ContainsTrench
#     - CoveredOrProtectedWithMaterials
#     - CropRelatedInfo
#     - DiffersFrom
#     - EdgeCreation
#     - ExposureEffectOnDevelopment
#     - ExtensionRelationship
#     - FearOfPests
#     - Follows
#     - GrowInWinter
#     - GrowthRateRelationship
#     - GrowthStageRelatedTo
#     - HairConditionFavorableForGrowth
#     - HasCostlyAspect
#     - HasDimensionalProperty
#     - HasPuttyOrPulley
#     - HasRelationshipWith
#     - HasStructuralTimbers
#     - HeatRelatedInteraction
#     - HypernymOf
#     - IntermarriagePattern
#     - LettuceNeverReplaced
#     - LettuceRelationship
#     - LocatedInOrAt
#     - LocatedInParis
#     - LocationAssociation
#     - MarketingRelation
#     - MilledToBleach
#     - MonthlyTiming
#     - MulchRelated
#     - NativeOrigin
#     - NegativeAssociation
#     - NegativelyAffectsGrowth
#     - OccupiesSpaceOf
#     - OrientationRelationship
#     - PartOf
#     - PeasCultivationPractices
#     - PlantabilityStatus
#     - PlantedIn
#     - PlantingOrHarvestingMethod
#     - PracticesInOrRelatedTo
#     - ProductionRelation
#     - ProneToDegeneration
#     - PruneOrCut
#     - RaisedOrEnhancedAt
#     - ReceivedBy
#     - RelatedToEconomicInformation
#     - RelatedToFarmingPractice
#     - Removed
#     - RentsAt
#     - RequiresConditionalRemoval
#     - ResearchInitiation
#     - RetainsSeedViabilityFor
#     - SeasonAssociatedEvents
#     - SeasonalChervilActivity
#     - SeasonalRelatedness
#     - SeedingRelatedState
#     - SeparatedBy
#     - SoilConditionReasonsForNoTransplanting
#     - SpreadBy
#     - SproutsFromOrIn
#     - TemporalAssociation
#     - ThinningMethodOrTool
#     - TimestampCreated
#     - TransportationRelation
#     - TreatedWithSomething
#     - UncertainOrDifficultToDetermine
#     - UsedWithOrBy
#     - VarietyOf
#     - WateringRelation
#     - YieldingInto
